/*
Base structure generated by gltfjsx 6.5.3:
  npx gltfjsx public/models/juke-opt.glb --types --keepnames --keepgroups
then edited: every part has a ref, shares one toon material and gets an outline.
*/
import * as THREE from 'three'
import { useEffect, useImperativeHandle, useMemo, useRef, type ReactNode, type Ref } from 'react'
import { useFrame, useThree, type ThreeElements } from '@react-three/fiber'
import { Outlines, useGLTF } from '@react-three/drei'
import { button, folder, useControls } from 'leva'
import type { GLTF } from 'three-stdlib'
import { createToonMaterial, makeGradientMap } from './toonMaterial'
import { lightRig } from '../scene/lightRig'
import { Blush, Brow } from './Brows'
import { FACE } from './config'
import { EyePlate } from './EyePlate'
import { FaceRig } from './faceRig'
import { EXPRESSION_NAMES, type ExpressionName } from './expressions'
import { useJukeStore } from './useJukeStore'
import { applyAlive, applyPose, emitMoodParticles } from './alive'
import { BEHAVIOR_NAMES, BehaviorDirector, type BehaviorCtx } from './behaviors'
import { createPose } from './pose'
import { handleClick, hotspotOf } from './interactions'
import { dvdFocus } from '../dvd/dvdState'
import { isLocked } from '../transitions/transitionStore'
import { SLOT, jukeApi } from './jukeApi'
import { HOVER } from '../dvd/config'

export const MODEL_URL = '/models/juke-opt.glb'

// Rest positions of the speakers and caps (head space / speaker space).
const SPEAKER_L: [number, number, number] = [-0.22026, 0.16277, 0.09135]
const SPEAKER_R: [number, number, number] = [0.21583, 0.16263, 0.09193]
const CAP_L: [number, number, number] = [-0.0015, 0.00078, 0.03882]
const CAP_R: [number, number, number] = [0.00359, -0.00518, 0.0378]

export const PART_NAMES = [
  'head',
  'speaker_L',
  'speaker_L_cap',
  'speaker_R',
  'speaker_R_cap',
  'button_1',
  'button_2',
  'button_3',
  'button_4',
  'handle',
  'handle_grip',
  'cassette_door',
  'cassette_eye_L',
  'cassette_eye_R',
  'torso',
  'hand_L',
  'hand_R',
  'leg_L',
  'leg_R',
  'shoe_L',
  'shoe_R',
  'shoe_L_tip',
  'shoe_R_tip',
] as const

export type PartName = (typeof PART_NAMES)[number]
export type JukeParts = Record<PartName, THREE.Mesh>

export type JukeHandle = {
  root: THREE.Group
  parts: JukeParts
}

type GLTFResult = GLTF & {
  nodes: Record<PartName, THREE.Mesh>
  materials: { juke_mat: THREE.MeshStandardMaterial }
}

type Base = { position: THREE.Vector3; rotation: THREE.Euler; scale: THREE.Vector3 }

type JukeProps = Omit<ThreeElements['group'], 'ref'> & { ref?: Ref<JukeHandle> }

export function Juke({ ref, ...props }: JukeProps) {
  const { nodes, materials } = useGLTF(MODEL_URL) as unknown as GLTFResult
  const root = useRef<THREE.Group>(null!)
  const parts = useRef({} as JukeParts)
  const base = useRef({} as Record<PartName, Base>)

  const look = useControls('Juke look', {
    ramp: folder({
      shadow: { value: 0.35, min: 0, max: 1, step: 0.01 },
      mid: { value: 0.62, min: 0, max: 1, step: 0.01 },
      light: { value: 0.88, min: 0, max: 1, step: 0.01 },
      steps: { value: 4, options: [3, 4] },
    }),
    rim: folder({
      rimColor: '#ff9a3c',
      rimStrength: { value: 0.4, min: 0, max: 2, step: 0.01 },
    }),
    specular: folder({
      specColor: '#ffe2b8',
      specStrength: { value: 0.35, min: 0, max: 2, step: 0.01 },
    }),
    outline: folder({
      outlineColor: '#120c08',
      // In pixels (drei's non-screenspace mode offsets in clip space).
      outlineThickness: { value: 2.2, min: 0, max: 8, step: 0.1 },
    }),
  })

  const gradient = useMemo(
    () =>
      makeGradientMap(
        look.steps === 3 ? [look.shadow, look.mid, 1] : [look.shadow, look.mid, look.light, 1],
      ),
    [look.shadow, look.mid, look.light, look.steps],
  )
  const { material, uniforms } = useMemo(
    () => createToonMaterial(materials.juke_mat, gradient),
    [materials.juke_mat], // eslint-disable-line react-hooks/exhaustive-deps
  )
  useEffect(() => {
    material.gradientMap = gradient
    material.needsUpdate = true
  }, [material, gradient])

  useEffect(() => {
    uniforms.uRimColor.value.set(look.rimColor)
    uniforms.uRimStrength.value = look.rimStrength
    uniforms.uSpecColor.value.set(look.specColor)
    uniforms.uSpecStrength.value = look.specStrength
  }, [uniforms, look.rimColor, look.rimStrength, look.specColor, look.specStrength])

  // --- Face -----------------------------------------------------------------
  const rig = useMemo(() => new FaceRig(), [])
  const expression = useJukeStore((s) => s.expression)
  const blinkRequest = useJukeStore((s) => s.blinkRequest)
  const soft = useJukeStore((s) => s.soft)
  useEffect(() => {
    rig.expression = expression
  }, [rig, expression])
  useEffect(() => {
    rig.soft = soft
    rig.softWeight = HOVER.expressionWeight
  }, [rig, soft])
  useEffect(() => {
    if (blinkRequest) rig.blink()
  }, [rig, blinkRequest])
  // --- Body: pose offsets (GSAP) + random behaviours ---------------------------
  const pose = useMemo(() => createPose(PART_NAMES), [])
  const behaviorCtx = useRef<BehaviorCtx | null>(null)
  const director = useMemo(() => new BehaviorDirector(() => behaviorCtx.current), [])
  useEffect(() => {
    if (import.meta.env.DEV) (window as unknown as { __director: BehaviorDirector }).__director = director
    jukeApi.director = director
    jukeApi.ctx = () => behaviorCtx.current
  }, [director])

  useEffect(() => {
    const onActivity = () => {
      rig.pointerMoved(performance.now() / 1000)
      director.onActivity()
    }
    const events = ['pointermove', 'pointerdown', 'wheel', 'keydown'] as const
    for (const e of events) window.addEventListener(e, onActivity)
    return () => {
      for (const e of events) window.removeEventListener(e, onActivity)
    }
  }, [rig, director])

  useControls(
    'Behaviors',
    Object.fromEntries([
      ...BEHAVIOR_NAMES.map((b) => [b, button(() => director.play(b))]),
      ['sleep', button(() => director.fallAsleep())],
      ['wake', button(() => director.wake())],
    ]),
  )

  useControls('Face', {
    expression: {
      value: 'neutral' as ExpressionName,
      options: EXPRESSION_NAMES,
      onChange: (v: ExpressionName) => useJukeStore.getState().setExpression(v),
    },
    blink: button(() => useJukeStore.getState().blink()),
  })

  // Face geometry derived from the speakers (eye plates, brows, blush).
  const face = useMemo(() => {
    const sb = nodes.speaker_L.geometry.boundingBox ?? (nodes.speaker_L.geometry.computeBoundingBox(), nodes.speaker_L.geometry.boundingBox!)
    const half = sb.getSize(new THREE.Vector3()).multiplyScalar(0.5)
    const plateRadius = Math.min(half.x, half.y) * FACE.plateRadius
    const speakerPos = { L: SPEAKER_L, R: SPEAKER_R }
    const brow = (s: 'L' | 'R') =>
      new THREE.Vector3(speakerPos[s][0], speakerPos[s][1] + half.y, speakerPos[s][2] + sb.max.z)
    const blush = (s: 'L' | 'R'): [number, number, number] => [
      speakerPos[s][0] * 0.82,
      speakerPos[s][1] - half.y - 0.012,
      speakerPos[s][2] + sb.max.z * 0.5,
    ]
    return { plateRadius, browL: brow('L'), browR: brow('R'), blushL: blush('L'), blushR: blush('R') }
  }, [nodes])

  // Pivot tester: nudge any part on top of its rest pose to check hinges.
  const pivot = useControls('Pivots (debug)', {
    part: { value: 'cassette_door' as PartName, options: [...PART_NAMES] },
    rotX: { value: 0, min: -Math.PI, max: Math.PI, step: 0.01 },
    rotY: { value: 0, min: -Math.PI, max: Math.PI, step: 0.01 },
    rotZ: { value: 0, min: -Math.PI, max: Math.PI, step: 0.01 },
    offY: { value: 0, min: -0.05, max: 0.05, step: 0.001 },
  })

  // Remember every part's rest transform once the refs are attached.
  useEffect(() => {
    for (const name of PART_NAMES) {
      const p = parts.current[name]
      base.current[name] = {
        position: p.position.clone(),
        rotation: p.rotation.clone(),
        scale: p.scale.clone(),
      }
    }
  }, [])

  useImperativeHandle(ref, () => ({ root: root.current, parts: parts.current }), [])

  const camera = useThree((st) => st.camera)
  useEffect(() => {
    behaviorCtx.current = {
      pose,
      rig,
      parts: parts.current,
      root: root.current,
      camera,
      rest: (name) => base.current[name].position,
    }
  }, [pose, rig, camera])

  const tmp = useMemo(() => new THREE.Vector3(), [])
  const tmp2 = useMemo(() => new THREE.Vector3(), [])
  useFrame(({ camera, pointer, clock }, dt) => {
    const P = parts.current
    const B = base.current
    if (!B.head) return
    const now = performance.now() / 1000
    const t = clock.elapsedTime

    // Light directions -> view space for the toon shader.
    uniforms.uKeyDir.value.copy(tmp.copy(lightRig.keyDir).transformDirection(camera.matrixWorldInverse))
    uniforms.uRimDir.value.copy(tmp.copy(lightRig.rimDir).transformDirection(camera.matrixWorldInverse))

    // Every layer below starts from the rest pose.
    for (const name of PART_NAMES) {
      P[name].position.copy(B[name].position)
      P[name].rotation.copy(B[name].rotation)
      P[name].scale.copy(B[name].scale)
    }
    const R = root.current
    R.position.set(0, 0, 0)
    R.rotation.set(0, 0, 0)
    R.scale.setScalar(1)

    // Gaze: cursor offset from the face, in screen space — or the hovered DVD.
    if (dvdFocus.object) {
      rig.pointerMoved(now)
      dvdFocus.object.getWorldPosition(tmp2).project(camera)
      P.cassette_door.getWorldPosition(tmp).project(camera)
      rig.setCursorOffset(tmp2.x - tmp.x, tmp2.y - tmp.y)
    } else if (!rig.isIdle(now)) {
      P.cassette_door.getWorldPosition(tmp).project(camera)
      rig.setCursorOffset(pointer.x - tmp.x, pointer.y - tmp.y)
    }
    rig.update(now, Math.min(dt, 0.1))

    // Head follows the gaze (max ~10°) plus the expression's own tilt.
    P.head.rotation.y += rig.headLook.x
    P.head.rotation.x += -rig.headLook.y + rig.headPose.pitch
    P.head.rotation.z += rig.headPose.roll

    // Breathing, floating hands, bass thump, weight shift, dance/sleep layers.
    applyAlive(P, R, pose, t)

    // Cassette eyes: a tiny second face that echoes the main one.
    const cs = rig.cassette
    const blinkSquash = 1 - 0.85 * rig.blinkAmount
    for (const [name, phase] of [['cassette_eye_L', 0], ['cassette_eye_R', 0.6]] as const) {
      const p = P[name]
      p.scale.set(cs.scale, cs.scale * cs.squash * blinkSquash, cs.scale).multiply(B[name].scale)
      p.position.y += Math.abs(Math.sin(t * cs.bounceSpeed + phase)) * cs.bounce
    }

    // GSAP-driven behaviour offsets on top.
    applyPose(P, R, pose, PART_NAMES)
    director.update(now)
    emitMoodParticles(P, rig, pose, t, Math.min(dt, 0.1))

    // Pivot tester (dev).
    const pp = P[pivot.part]
    pp.rotation.x += pivot.rotX
    pp.rotation.y += pivot.rotY
    pp.rotation.z += pivot.rotZ
    pp.position.y += pivot.offY
  })

  const setPart = (name: PartName) => (m: THREE.Mesh | null) => {
    if (m) parts.current[name] = m
  }

  const ol = <Outlines thickness={look.outlineThickness} color={look.outlineColor} angle={Math.PI} />

  const part = (name: PartName, position: [number, number, number], children?: ReactNode) => (
    <mesh
      name={name}
      ref={setPart(name)}
      geometry={nodes[name].geometry}
      material={material}
      position={position}
      castShadow
      receiveShadow
    >
      {name.endsWith('_cap') ? null : ol}
      {children}
    </mesh>
  )

  return (
    <group {...props} dispose={null}>
      <group
        name="Juke"
        ref={root}
        onClick={(e) => {
          e.stopPropagation()
          if (isLocked()) return
          const h = hotspotOf(e.object)
          if (h) handleClick(director, h)
        }}
        onPointerOver={(e) => {
          e.stopPropagation()
          document.body.style.cursor = 'pointer'
        }}
        onPointerOut={() => {
          document.body.style.cursor = ''
        }}
      >
        {part('hand_L', [-0.22547, -0.30775, -0.01382])}
        {part(
          'leg_L',
          [-0.12371, -0.33427, -0.02502],
          part('shoe_L', [-0.0117, -0.16573, 0.03617], part('shoe_L_tip', [0.02182, 0.06567, 0.03478])),
        )}
        {part('torso', [-0.00672, -0.36203, -0.01977])}
        {part(
          'leg_R',
          [0.113, -0.33344, -0.02229],
          part('shoe_R', [0.01465, -0.16656, 0.03354], part('shoe_R_tip', [-0.02419, 0.05768, 0.03517])),
        )}
        {part('hand_R', [0.20873, -0.30741, -0.01423])}
        {part(
          'head',
          [-0.00053, -0.04588, -0.02414],
          <>
            {part(
              'speaker_L',
              SPEAKER_L,
              <>
                {part('speaker_L_cap', CAP_L)}
                <EyePlate
                  side="L"
                  rig={rig}
                  speaker={nodes.speaker_L.geometry}
                  cap={nodes.speaker_L_cap.geometry}
                  capPosition={CAP_L}
                  gradientMap={gradient}
                />
              </>,
            )}
            <Brow side="L" rig={rig} anchor={face.browL} plateRadius={face.plateRadius} />
            <Blush rig={rig} position={face.blushL} size={face.plateRadius * 1.1} />
            {part('button_1', [-0.10039, 0.31469, 0.1116])}
            {part('button_2', [-0.03575, 0.31408, 0.11204])}
            {part('button_3', [0.02514, 0.31379, 0.11082])}
            {part('button_4', [0.08922, 0.31384, 0.11152])}
            {part(
              'cassette_door',
              [-0.00728, 0.08305, 0.14069],
              <>
                {part('cassette_eye_L', [-0.0506, 0.05865, -0.01969])}
                {part('cassette_eye_R', [0.05435, 0.05867, -0.01982])}
              </>,
            )}
            <CassetteSlot />
            {part('handle', [-0.01616, 0.31335, 0.00427], part('handle_grip', [-0.0008, 0.17265, 0.00245]))}
            {part(
              'speaker_R',
              SPEAKER_R,
              <>
                {part('speaker_R_cap', CAP_R)}
                <EyePlate
                  side="R"
                  rig={rig}
                  speaker={nodes.speaker_R.geometry}
                  cap={nodes.speaker_R_cap.geometry}
                  capPosition={CAP_R}
                  gradientMap={gradient}
                />
              </>,
            )}
            <Brow side="R" rig={rig} anchor={face.browR} plateRadius={face.plateRadius} />
            <Blush rig={rig} position={face.blushR} size={face.plateRadius * 1.1} />
          </>,
        )}
      </group>
    </group>
  )
}

/**
 * The dark cassette compartment revealed when the door opens (the model is solid
 * behind the door). Hidden inside the door while it's closed.
 */
function CassetteSlot() {
  const map = useMemo(() => {
    const w = 256
    const h = Math.round((w * SLOT.size[1]) / SLOT.size[0])
    const cv = document.createElement('canvas')
    cv.width = w
    cv.height = h
    const g = cv.getContext('2d')!
    // Recess: lighter bevel at the edges, near-black in the middle.
    const grd = g.createRadialGradient(w / 2, h / 2, 10, w / 2, h / 2, w * 0.6)
    grd.addColorStop(0, '#0b0806')
    grd.addColorStop(1, '#2a1d12')
    g.fillStyle = grd
    g.fillRect(0, 0, w, h)
    g.strokeStyle = '#4a3420'
    g.lineWidth = 8
    g.strokeRect(4, 4, w - 8, h - 8)
    // Two tape spindles.
    for (const x of [w * 0.32, w * 0.68]) {
      g.fillStyle = '#3b2a1a'
      g.beginPath()
      g.arc(x, h * 0.55, h * 0.17, 0, Math.PI * 2)
      g.fill()
      g.fillStyle = '#0b0806'
      g.beginPath()
      g.arc(x, h * 0.55, h * 0.07, 0, Math.PI * 2)
      g.fill()
    }
    const t = new THREE.CanvasTexture(cv)
    t.colorSpace = THREE.SRGBColorSpace
    return t
  }, [])
  return (
    <mesh position={SLOT.center}>
      <planeGeometry args={SLOT.size} />
      <meshBasicMaterial map={map} toneMapped={false} />
    </mesh>
  )
}

useGLTF.preload(MODEL_URL)
