import type { ExpressionName } from '../juke/expressions'
import media from './media.generated.json'

/** A large visual on the project page (generated by `npm run import-projects`). */
export type MediaItem =
  | { type: 'image'; src: string; small?: string; width: number; height: number; caption: string }
  | { type: 'video'; src: string; poster: string; width: number; height: number; caption: string }

export type Side = 'A' | 'B' | 'C'

/** Names shown on the side switch. */
export const SIDES: Record<Side, string> = {
  A: 'Print & Posters',
  B: 'Brands & Motion',
  C: 'Social Medias & Contacts',
}

/** The order the side switch steps through. */
export const SIDE_ORDER: Side[] = ['A', 'B', 'C']

export type Project = {
  slug: string
  title: string
  /** One short sentence — shown as two lines on the cover. */
  tagline: string
  /** Back cover and project page. */
  description: string
  /** DVD cover art, ~800×880. A placeholder illustration is drawn if it's missing. */
  thumbnail?: string
  /** Small images for the back of the case (defaults to the gallery). */
  screenshots?: string[]
  /** Big visuals on the project page. */
  gallery?: MediaItem[]
  /**
   * false = the artwork already carries its own title, so the cover shows it whole
   * and puts the project name in the bottom band instead of over the art.
   */
  coverTitle?: boolean
  /** Which side of the "tape" the DVD sits on (A and B are flipped with a switch). */
  side: Side
  color: string
  icon: string
  tech: string[]
  links: { live?: string; github?: string }
  jukeExpression: ExpressionName
  /** A contact DVD: clicking it opens this address (new tab) instead of a project page. */
  href?: string
  /** Small logo image drawn in the cover badge and on the spine instead of the icon. */
  logo?: string
}

const gallery = (slug: string) => ((media as Record<string, MediaItem[]>)[slug] ?? []) as MediaItem[]

const withMedia = (p: Omit<Project, 'gallery' | 'thumbnail'>): Project => {
  const g = gallery(p.slug)
  return {
    ...p,
    thumbnail: `/projects/${p.slug}/thumb.jpg`,
    gallery: g,
    // Back cover: the gallery images after the main one (or the video poster).
    screenshots:
      p.screenshots ??
      g
        .slice(g.length > 1 ? 1 : 0)
        .map((m) => (m.type === 'image' ? (m.small ?? m.src) : m.poster))
        .slice(0, 3),
  }
}

// Your projects. Images/videos come from scripts/projects-manifest.json → run
// `npm run import-projects` after changing them. See public/projects/README.md.
export const PROJECTS: Project[] = [
  withMedia({
    slug: 'white-noise',
    side: 'A',
    title: 'White Noise',
    tagline: 'A loud, glitchy book cover for Don DeLillo’s novel.',
    description:
      'Book cover design for Don DeLillo’s White Noise. The title is set in heavy condensed type that breaks apart into static, numbers and symbols — a visual take on the novel’s constant background hum of media, ads and consumer culture. Shown as the flat cover and as a printed hardcover mockup.',
    coverTitle: false,
    color: '#d1322b',
    icon: '📖',
    tech: ['Book Cover', 'Typography', 'Mockup'],
    links: {},
    jukeExpression: 'thinking',
  }),
  withMedia({
    slug: 'kanye-swiss-style',
    side: 'A',
    title: 'Kanye West: Swiss Style',
    tagline: '“Through the Wire”, told on a strict Swiss grid.',
    description:
      'An editorial magazine spread about Kanye West’s debut single “Through the Wire”, built on a strict Swiss-style grid. Clean columns, large serif headlines and black-and-white photography keep a dramatic story calm, readable and rhythmic. Part of the “Making the Grid” project at Bahçeşehir University.',
    coverTitle: false,
    color: '#b5121b',
    icon: '📰',
    tech: ['Editorial Design', 'Swiss Style', 'Grid Systems'],
    links: {},
    jukeExpression: 'proud',
  }),
  withMedia({
    slug: 'kanye-break-the-grid',
    side: 'A',
    title: 'Kanye West: Break the Grid',
    tagline: 'The same story — with the grid torn apart.',
    description:
      'The loud counterpart to the Swiss-style spread: the same “Through the Wire” story, but this time the grid is broken on purpose. Cut-out type, collage, the American flag and Billboard references collide into expressive posters full of energy.',
    coverTitle: false,
    color: '#f6d63c',
    icon: '✂️',
    tech: ['Collage', 'Experimental Type', 'Poster Design'],
    links: {},
    jukeExpression: 'excited',
  }),
  withMedia({
    slug: 'mola-identity',
    side: 'B',
    title: 'Mola Corporate Identity',
    tagline: 'A warm, cozy identity for a coffee brand.',
    description:
      'Corporate identity for Mola — a coffee brand whose name means “break” in Turkish. A steaming cup hides inside the O of the logo, and a warm coffee-brown and deep black palette carries the brand across the app icon, cups, packaging, signage and staff badges.',
    coverTitle: false,
    color: '#b38f6f',
    icon: '☕',
    tech: ['Brand Identity', 'Logo Design', 'Packaging'],
    links: {},
    jukeExpression: 'love',
  }),
  withMedia({
    slug: 'who-i-am',
    side: 'B',
    title: 'Who I Am',
    tagline: 'Puffy 3D letters floating through the clouds.',
    coverTitle: false,
    description:
      'A short 3D motion piece. Soft, inflatable “WHO I AM” letters and a glossy puffer jacket drift through a dreamy sky full of clouds — an exploration of soft materials, light and camera movement.',
    color: '#4fb3e3',
    icon: '☁️',
    tech: ['3D Animation', 'Motion Design'],
    links: {},
    jukeExpression: 'happy',
  }),
  withMedia({
    slug: 'home-tour',
    side: 'B',
    title: 'Home Tour Video',
    tagline: 'A modern home, shown in twenty seconds.',
    description:
      'A promotional home tour video. Smooth camera moves glide from the exterior through the bedroom, bathroom and living spaces, tied together with clean motion graphics and an animated closing call to action.',
    color: '#c7884a',
    icon: '🏠',
    tech: ['Video Editing', 'Motion Graphics'],
    links: {},
    jukeExpression: 'wink',
  }),
  withMedia({
    slug: 'didot-specimen',
    side: 'A',
    title: 'Didot Type Specimen',
    tagline: 'A bold specimen for a hairline serif.',
    description:
      'A type specimen celebrating Didot, the high-contrast modern serif drawn by Firmin Didot around 1790. Hairline serifs, dramatic thick-and-thin strokes and a striking magenta-on-black layout show off the typeface’s elegance — from a giant display “f” to the full alphabet, numerals and glyphs. Made at Bahçeşehir University.',
    coverTitle: false,
    color: '#a43fd6',
    icon: '🔤',
    tech: ['Type Specimen', 'Typography', 'Editorial Design'],
    links: {},
    jukeExpression: 'proud',
  }),
  withMedia({
    slug: 'unknown-place',
    side: 'A',
    title: 'Unknown Place',
    tagline: 'Lost in space, under the flying saucers.',
    description:
      'A sci-fi poster for “Unknown Place”: an astronaut looks up as flying saucers drift through a glowing nebula. Classic serif title typography meets photo-collage space imagery for a mysterious, cinematic mood.',
    coverTitle: false,
    color: '#12a54a',
    icon: '🛸',
    tech: ['Poster Design', 'Photo Collage', 'Typography'],
    links: {},
    jukeExpression: 'surprised',
  }),
  withMedia({
    slug: 'scarface-poster',
    side: 'A',
    title: 'Scarface',
    tagline: 'Money, power and fire on a dollar bill.',
    description:
      'An alternative film poster for Scarface. A crumpled dollar bill becomes the canvas: a rifle, burning cigars and flames are drawn over it, summing up the film’s story of money, power and violence in a single image.',
    coverTitle: false,
    color: '#1d1a1a',
    icon: '💵',
    tech: ['Film Poster', 'Illustration', 'Concept'],
    links: {},
    jukeExpression: 'suspicious',
  }),
  withMedia({
    slug: 'messi-illustration',
    side: 'A',
    title: 'Messi Illustration',
    tagline: 'A colourful tribute to the number 10.',
    description:
      'A World Cup illustration for Lionel Messi: the trophy, the ball, a big golden 10 and the GOAT itself over a waving blue-and-white pattern — a loud, colourful celebration of his World Cup triumph.',
    coverTitle: false,
    color: '#6aa6e4',
    icon: '⚽',
    tech: ['Illustration', 'Digital Art'],
    links: {},
    jukeExpression: 'love',
  }),
  withMedia({
    slug: 'linka-identity',
    side: 'B',
    title: 'LINKA',
    tagline: 'Brand identity for a dating app with brains.',
    description:
      'Brand identity for LINKA, an e-dating app for students and academics — “Link + Academic(a)”. A soft A-shaped symbol, a handwritten logotype and a lilac-to-indigo palette (#BF78EC, #5B5FEF) carry the brand across app icons, screens and lifestyle mockups.',
    coverTitle: false,
    color: '#5b5fef',
    icon: '💜',
    tech: ['Brand Identity', 'Logo Design', 'App Branding'],
    links: {},
    jukeExpression: 'shy',
  }),
  withMedia({
    slug: 'music-video',
    side: 'B',
    title: 'Animated Music Video',
    tagline: 'Hand-drawn line art moving to the music.',
    description:
      'A hand-drawn animated music video. A knight’s helmet, watching eyes, a crying golden-haired figure, burning forests, rivers and a blazing sun flow into one another in clean line art and flat colour, following the rhythm of the song.',
    color: '#f0b31f',
    icon: '🎵',
    tech: ['2D Animation', 'Illustration', 'Music Video'],
    links: {},
    jukeExpression: 'excited',
  }),
  withMedia({
    slug: 'fight-club-titles',
    side: 'B',
    title: 'Fight Club Title Sequence',
    tagline: 'Opening credits carved into soap, brick and grime.',
    description:
      'An alternative opening title sequence for David Fincher’s Fight Club. The credits are pressed into a pink 3D soap bar, smashed onto brick walls, scratched into red grunge textures and folded out of paper — a loud, physical take on the film’s mood.',
    coverTitle: false,
    color: '#d8232a',
    icon: '🎬',
    tech: ['Title Design', 'Motion Graphics', '3D'],
    links: {},
    jukeExpression: 'focused',
  }),
  withMedia({
    slug: 'fight-club-soap',
    side: 'B',
    title: 'Fight Club Soap',
    tagline: 'A pink soap bar, a famous name.',
    description:
      'A short 3D logo reveal: a glossy pink soap bar turns in the dark until the embossed FIGHT CLUB title faces the camera. Modelled, lit and rendered in 3D for the title sequence.',
    coverTitle: false,
    color: '#e7a3bf',
    icon: '🧼',
    tech: ['3D Modelling', 'Lighting', 'Rendering'],
    links: {},
    jukeExpression: 'wink',
  }),
]

// Side C: contact DVDs. Clicking one goes straight to the profile / a new message.
const contact = (p: Omit<Project, 'side' | 'coverTitle' | 'thumbnail' | 'logo' | 'links' | 'screenshots'>): Project => ({
  ...p,
  side: 'C',
  coverTitle: false,
  thumbnail: `/contacts/${p.slug}.svg`,
  logo: `/contacts/${p.slug}-logo.svg`,
  screenshots: [],
  links: {},
})

export const CONTACTS: Project[] = [
  contact({
    slug: 'instagram',
    title: 'Instagram',
    tagline: '@kaanaccr — posters, process and work in progress.',
    description:
      'Follow along on Instagram for new posters, design experiments and behind-the-scenes process shots. Click the DVD to open my profile.',
    color: '#d6249f',
    icon: '📸',
    tech: ['@kaanaccr', 'Follow'],
    href: 'https://www.instagram.com/kaanaccr/',
    jukeExpression: 'love',
  }),
  contact({
    slug: 'teams',
    title: 'Microsoft Teams',
    tagline: 'Chat with me on Teams.',
    description:
      'Reach me on Microsoft Teams for school projects, collaborations or a quick call. Click the DVD to start a chat with kaan.acar@bahcesehir.edu.tr.',
    color: '#5b5fc7',
    icon: '💬',
    tech: ['Chat', 'Call'],
    href: 'https://teams.microsoft.com/l/chat/0/0?users=kaan.acar@bahcesehir.edu.tr',
    jukeExpression: 'happy',
  }),
  contact({
    slug: 'linkedin',
    title: 'LinkedIn',
    tagline: 'Kaan Acar — let’s connect.',
    description:
      'My professional profile: education, experience and projects. Click the DVD to open my LinkedIn profile and connect.',
    color: '#0a66c2',
    icon: '💼',
    tech: ['Connect', 'Experience'],
    href: 'https://www.linkedin.com/in/kaan-acar-b93b703b6/',
    jukeExpression: 'proud',
  }),
  contact({
    slug: 'gmail',
    title: 'Gmail',
    tagline: 'acarkaan768@gmail.com',
    description:
      'Got a project, a question or just want to say hi? Click the DVD to write me an email at acarkaan768@gmail.com.',
    color: '#ea4335',
    icon: '✉️',
    tech: ['Email', 'Say hi'],
    href: 'https://mail.google.com/mail/?view=cm&fs=1&to=acarkaan768@gmail.com',
    jukeExpression: 'excited',
  }),
]
